### ISSUE TITLE
condaenv is broken in 26 at least with Miniconda 3

### ISSUE THREAD

**Issue by throwable-one** [JetBrains/gradle-python-envs#30]
See

https://github.com/JetBrains/gradle-python-envs/commit/cc1be34411aa5708c9e2238bc3edfd30c9302b4d#r31733255

**Comment by ARostovsky** [comment]
Hi @throwable-one!
Please try 28 version

@anuraaga env.name used in conda definition is already used for directory creation, so there is no need to specify env.name explicitly in command
